apiVersion: apps/v1
kind: Deployment
metadata:
  name: anandadf-profile-be
  namespace: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-be
  template:
    metadata:
      labels:
        app: profile-be
    spec:
      containers:
      - name: backend
        image: docker-registry.anandadf.my.id/portfolio/backend:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "600Mi"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-auth
      nodeSelector:
        kubernetes.io/arch: "amd64"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-be
  namespace: profile
spec:
  selector:
    app: profile-be
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080